feat(UI): create navbar
vohoanglong0107/ticket-booking-app pull request #48
Opened 2022-11-07 08:42 UTC by vanthai0508

## Short description

## Issue ticket number and link

## Additional information

2022-11-07 16:04 UTC, vohoanglong0107 requested changes
Chỉnh chút nữa là mượt mà như Hà Thái hầy

2022-11-07 16:04 UTC, vohoanglong0107 commented on components/Navbar/NavItem.tsx
> +    <Link legacyBehavior href={href}>
Cái Legacy benavior này để làm chi Thái hè

2022-11-07 16:04 UTC, vohoanglong0107 commented on styles/navbar.css
> +@import url('https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;700&display=swap');
File Navbar này m để vô trong folder Navbar của Component luôn được không, Với m đổi tên lại thành Navbar.css luôn hì

2022-11-07 16:04 UTC, vohoanglong0107 commented on components/Navbar/Navbar.tsx
> +
Với m import cái Navbar css vô đây hầy, vô đây là sau giả sử ai muốn dùng component ni là không cần phải import thêm cái css riêng nữa mà import component thôi là đủ

2022-11-07 16:04 UTC, vohoanglong0107 commented on pages/_app.tsx
> +import "../styles/navbar.css";
Import vô trong Navbar component hì

2022-11-07 16:09 UTC, vanthai0508 commented on components/Navbar/NavItem.tsx
> +    <Link legacyBehavior href={href}>
t đọc tài liệu thì nó nói cái này hỗ trợ cho onMouse onCLick , nếu bỏ nó thì nó bị bắt lỗi chỗ link đó

2022-11-08 10:28 UTC, vohoanglong0107 approved these changes

2022-11-08 10:28 UTC, merged