feat(UI): add show available games components
vohoanglong0107/ticket-booking-app pull request #58
Opened 2022-11-09 13:30 UTC by vanthai0508

## Short description

## Issue ticket number and link
Close (#20 )

## Additional information

2022-11-10 04:59 UTC, vohoanglong0107 requested changes
M check package.json với package-lock.json hầy

2022-11-10 04:59 UTC, vohoanglong0107 commented on components/View/View-source.tsx
> +import ImageList from "@mui/material/ImageList";
Chỗ này m xài @mui mà m chưa install vào package.json với package-lock.json nè thái

2022-11-10 11:32 UTC, vanthai0508 commented on components/View/View-source.tsx
> +import ImageList from "@mui/material/ImageList";
k phải chưa install mà t k push 2 file nớ lên á long , do trên công ty t làm dự án k cho phép push 2 file nớ composer các kiểu nên t quên

2022-11-14 07:16 UTC, vohoanglong0107 approved these changes

2022-11-14 07:16 UTC, merged